### ISSUE TITLE
mdstore: format node's lastChecked datetime to be valid against schema

### ISSUE THREAD

**Issue by ldko** [unt-libraries/coda#36]
When writing the nodexml schema, we changed the lastChecked format to go along with xs:dateTime format. We should change the string set for [lastChecked](https://github.com/unt-libraries/coda/blob/master/coda/coda_mdstore/presentation.py#L433) to match this format. 

Should be like:
 `node.last_checked.strftime("%Y-%m-%dT%H:%M:%SZ")`

**Comment by ldko** [comment]
See discussion on #83.

**Comment by ldko** [comment]
I don't think the change made in [here](https://github.com/unt-libraries/coda/commit/8abd8d321e8e422221624718cb99952152ee27fd) validates against the nodexml schema because it requires the "T" as in "%Y-%m-%dT%H:%M:%S".

**Comment by runderwood** [comment]
@vphill @ldko The date fixes continue to ripple outward. It appears that in the `premis_event_service` app, datetimes have always just stripped out timezone data. It also appears that the app treats datetimes coming *out* of the database as UTC, though it's not clear to me that's the case -- it would be true only if every client *only* posts datetimes in UTC. More directly, offsets, zero or non, coming in get ignored while datetimes stored in the DB are assumed to have come in with a 00:00 offset.

Right now, in feature branches, dates are more accurately parsed in that they honor xs:DateTime offsets. But we don't store timezone data in the database. That's fine if we're okay with applying offsets on event datetimes so that we convert all datetimes to naive ones and assume they represent UTC.

So, should I just flatten all datetimes to UTC and store them as such, assuming everything in the database is UTC (I doubt this is true)? Or do we want to start saving timezone data (something that would be a very non-trivial change)?

**Comment by runderwood** [comment]
There were a lot of confounding factors here, including that the dev/testing environments with regard to times were quite different between PES and Coda. Things look good to me now in that `codalib` provides standard parse and format functions for naive and tz-aware datetimes such that the apps now handle `xsDateTime` strings correctly while not breaking existing conventions.

All of that to say I think this is solid in unt-libraries/coda@atom-related-fixes.
